# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojosecrets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='secret',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
