# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uvalidation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
